name = "contact-database-function"
compatibility_date = "2022-08-23"
main = "src/index.ts"

[[ d1_databases ]]
binding = "DB"
database_name = "CONTACT_DB"
database_id = "82f2622b-6f1e-41a5-a177-68bc2c19e35e"